### ISSUE TITLE
Remove Android code

### ISSUE THREAD

**Issue by 3vivekb** [codeforsanjose/SJPL-MealTally#1]

**Comment by cy19890513** [comment]
Hello, 

I am new here. What happen to the Android code. And remove them? This is my first comment. Ha

Thanks,
Yang

**Comment by robeau** [comment]
You should be able to do an `rm -rf` on the android folder and then add, commit, and push your code.

**Comment by cy19890513** [comment]
I successfully build the android app on android studio. it looks pretty cool to me.

Thanks,
Yang

![android image](https://cloud.githubusercontent.com/assets/5606275/23972396/d58ee0d0-098e-11e7-939c-ef5551827fd9.png)
