### ISSUE TITLE
Use Mailgun rather than Gmail?

### ISSUE THREAD

**Issue by clarle** [codeforsanjose/SJPL-MealTally#10]
Up for discussion, but I usually like using [Mailgun](https://www.mailgun.com/) rather than Gmail SMTP for sending emails out.

It's a bit easier for folks to set up compared to SMTP, and there's better analytics on the messages that are sent out.

@robeau What do you think?

**Comment by 3vivekb** [comment]
I got the gmail one to work on the first try with my personal.  I think we should leave it.

**Comment by robeau** [comment]
SMTP was just the first one I found. I haven't tried Mailgun (and haven't used SMTP for anything else) so if you think it's good Clarence, let's go for it.

**Comment by clarle** [comment]
I don't have a strong preference here. I'm okay with leaving it as is for now if it seemed easy to set up.
