### ISSUE TITLE
fix issues in npm audit

### ISSUE THREAD

**Issue by JMStudiosJoe** [codeforsanjose/SJPL-MealTally#101]
when installing project dependencies go through the npm audit tools to fix dependencies and update packages.

**Comment by darpham** [comment]
latest npm audit from develop branch
found 11 vulnerabilities (3 low, 3 moderate, 3 high, 2 critical)

opening branch to asses: https://github.com/codeforsanjose/SJPL-MealTally/pull/104

**Comment by darpham** [comment]
Last package for `npm audit` `html-pdf` package
https://github.com/codeforsanjose/SJPL-MealTally/pull/105

**Comment by darpham** [comment]
@JMStudiosJoe I believe we can close this now
All vulnerabilities are accounted for
