### ISSUE TITLE
reformat the Angularjs app.js file

### ISSUE THREAD

**Issue by cy19890513** [codeforsanjose/SJPL-MealTally#13]
I believe it is necessary to reconstruct the app.js file. it have like 20,000 lines of code. when you try to change something, it is lagging so much. basically can not add more code onto that file. Please reformat so we can add more features and maitenance.

**Comment by clarle** [comment]
Hey @cy19890513,

That file's generated by build tools and not human-generated.  It's using the files from this folder:

https://github.com/codeforsanjose/SJPL-MealTally/tree/master/webclient

Let me know if that makes it clearer, and cheers!

**Comment by cy19890513** [comment]
Ah. @clarle,

Thanks for the info. it does said /build/ in the path.

Thanks,
Yang
