### ISSUE TITLE
Consider recording video footage from end of line for backup tally measurements.

### ISSUE THREAD

**Issue by justinhester** [codeforsanjose/SJPL-MealTally#31]
I discussed this with Tomkia Price as a backup measurement in case the assigned volunteer should lose focus from the tallying task. However, she hinted there might be conflicts with library policy or ymca event restrictions.

This would be ideal though to possibly collect training data for a neural network that classifies images of people as meal categories (e.g. Adult, Children, Staff, etc.)

**Comment by JMStudiosJoe** [comment]
Would likely run into policy issues but could this be recorded through security cameras?

**Comment by JMStudiosJoe** [comment]
will continue this discussion when issue comes about, closing for now
