### ISSUE TITLE
Update README and make sure steps work for onboarding devs

### ISSUE THREAD

**Issue by justinhester** [codeforsanjose/SJPL-MealTally#36]
# Requirements:
- [ ] List dependencies (e.g. Ionic CLI, Typescript, etc.)
- [ ] Add step in "Running the web app locally" to set `MONGODB_URI` in Node (like in a `.env` file or in the current case on Heroku); replace confusing `$ MONGODB_URI=∆ node server.js` junk with `$ node server.js`

**Comment by justinhester** [comment]
https://gist.github.com/apolloclark/f0e3974601346883c731

**Comment by justinhester** [comment]
The last two commits contain issue typos. They were hard reset and replaced with the correct issue reference in 40f8302.

**Comment by JMStudiosJoe** [comment]
Definitely worked on this and the new process is working, please check out latest of development branch.
