### ISSUE TITLE
Implement @screenspan's marvel app ui.

### ISSUE THREAD

**Issue by justinhester** [codeforsanjose/SJPL-MealTally#42]
# Description
- [Marvel prototype: 25g0e5j](https://marvelapp.com/25g0e5j)

# Requirements
- [ ] Update src/pages
- [ ] Check for human presence as a login
  - `Name`: Justin Hester
  - `Code`: BananaMuffinCrumbs

**Comment by JMStudiosJoe** [comment]
Mobile UI is in progress but need that logo
