### ISSUE TITLE
Volunteer/Organizer application tabs

### ISSUE THREAD

**Issue by JMStudiosJoe** [codeforsanjose/SJPL-MealTally#55]
<img width="984" alt="screen shot 2018-03-20 at 8 48 44 am" src="https://user-images.githubusercontent.com/4028643/37665945-9727192e-2c1b-11e8-8513-ec488fe9d6fd.png">

There are three tabs along the bottom screen:

Home - meal tally - in progerss 
Log - 
Report -

**Comment by JMStudiosJoe** [comment]
@karencalpo

**Comment by karencalpo** [comment]
Are those the three screens you want created above? If so, these should be three separate issues.

**Comment by JMStudiosJoe** [comment]
@karencalpo agreed will make separate issues for each tab.

**Comment by JMStudiosJoe** [comment]
made separate issues for each needed tab
