### ISSUE TITLE
Make web design more user friendly

### ISSUE THREAD

**Issue by 3vivekb** [codeforsanjose/SJPL-MealTally#6]
The android app had a nice interface that was mobile friendly.  We should implement that in the webapp.

**Comment by robeau** [comment]
This will take some frontend skills. Will need CSS to match the mockup, and javascript to make the buttons add everything up nicely.

**Comment by justinhester** [comment]
Idea for this proposed in 25978ab9. The big side note though is that I had to code up the web client from scratch in Ionic 3.
