### ISSUE TITLE
PDF report generation

### ISSUE THREAD

**Issue by JMStudiosJoe** [codeforsanjose/SJPL-MealTally#72]
PDF generator using templates for easier PDF generation.

**Comment by JMStudiosJoe** [comment]
an update on this is reports sent to the YMCA might be excel documents instead of PDF.

**Comment by heggy231** [comment]
I am interested in working on this.

**Comment by JMStudiosJoe** [comment]
Turns out pdf reports are not what is needed excel reports are and have this completed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
