### ISSUE TITLE
Clicking "export" goes to "error" page

### ISSUE THREAD

**Issue by dpindrys** [codeforsanjose/SJPL-MealTally#77]
goes here:
https://mealtally-server.herokuapp.com/report/undefined

**Comment by JMStudiosJoe** [comment]
not able to reproduce was there an error in the node terminal window?

**Comment by JMStudiosJoe** [comment]
The error is on main site not local dev, issue is likely due to report/ not existing

**Comment by JMStudiosJoe** [comment]
Likely issue when reports was empty list have reports and report downloads, need to make sure there are reports in the list before making request.
