### ISSUE TITLE
New contributor can't navigate to sections of application

### ISSUE THREAD

**Issue by rossslaney** [codeforsanjose/SJPL-MealTally#78]
Hi, I am a resident of San Jose and a CS student. I was hoping to contribute to this project but I ran into a number of problems with understanding the project structure. 

I have a local environment set up and the project is running fine. Great job on docs for db setup and local start. However, I can't figure out how to navigate inside the actual application to the reporting section, or any of the mobile screens that I see in the current documentation. I can't find out how a user would navigate to the sections that most of the current issues are for. 

I am asking that you provide clearer guidance on the structure of the project and how to navigate the current state of the application.

E.G:
What happens when I login?
Before:
![image](https://user-images.githubusercontent.com/23709177/40334010-3ac5b1f6-5d10-11e8-9cc2-1011b8b9d95c.png)

After:
![image](https://user-images.githubusercontent.com/23709177/40334023-4e29b580-5d10-11e8-8bd5-341b83b9e3e2.png)

I can't find any new navigational options after logging in?

**Comment by JMStudiosJoe** [comment]
Hello Ross,

My name is Joseph I am one of leaf developers for this project have you
joined the slack group?

Regards,

- Joseph

**Comment by JMStudiosJoe** [comment]
To answer your questions quickly you need to be an admin user to get to
reports page.

**Comment by JMStudiosJoe** [comment]
In your local db your need to update your user to isAdmin true. Closing issue for now please connect with group on slack.
