### ISSUE TITLE
Incorrect headers/data in reports

### ISSUE THREAD

**Issue by dpindrys** [codeforsanjose/SJPL-MealTally#81]
Weekly (to ourknowledge) does not details such as "Meals available" or "Unused", but does need "Type" and "Library" specified. Top is current report export, below is excel doc that serves as a template:

![screen shot 2018-05-29 at 10 44 24 am](https://user-images.githubusercontent.com/1854573/40690387-bba2d42e-635b-11e8-85bc-e5267d2358fa.png)
![screen shot 2018-05-29 at 10 28 39 am](https://user-images.githubusercontent.com/1854573/40690388-bbbbd32a-635b-11e8-9bd4-447f62538501.png)

**Comment by JMStudiosJoe** [comment]
+1 emailed librarians and YMCA about current format waiting to hear back
