### ISSUE TITLE
Viewing -> Editing report, buttons remain

### ISSUE THREAD

**Issue by dpindrys** [codeforsanjose/SJPL-MealTally#82]
When viewing a report, then selecting "Edit", the edit modal appears but the buttons for viewing (edit/close) remain

Instead, a close button (X on top right/left?) should be at top, "Save" at bottom to save the edit

![screen shot 2018-05-29 at 1 03 18 pm](https://user-images.githubusercontent.com/1854573/40690501-48e909b6-635c-11e8-8081-9b12ee79f12f.png)
Above: eidt screen/modal
Below: view screen
![screen shot 2018-05-29 at 1 03 09 pm](https://user-images.githubusercontent.com/1854573/40690502-491da5ae-635c-11e8-9dc5-438da449810d.png)

**Comment by JMStudiosJoe** [comment]
+1 fixed
